/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AbstractModule } from "./AbstractModule";
export type { AbstractModuleUpgradeable } from "./AbstractModuleUpgradeable";
export type { IModule } from "./IModule";
export type { ModuleProxy } from "./ModuleProxy";
export type { TestModule } from "./TestModule";
